import Link from 'next/link'
import Wordmark from '@/components/Wordmark'

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="py-6" style={{ borderTop: '1px solid #E2DED8' }}>
      <h2 className="text-xl mb-3" style={{ fontFamily: 'Fraunces, serif' }}>{title}</h2>
      <div className="text-sm leading-relaxed" style={{ color: '#3d3c3c' }}>{children}</div>
    </section>
  )
}

export default function TermsPage() {
  return (
    <div style={{ backgroundColor: '#FAF8F5', minHeight: '100vh' }}>
      <nav className="sticky top-0 z-10 flex items-center justify-between px-8 py-4" style={{ backgroundColor: '#FAF8F5', borderBottom: '1px solid #E2DED8' }}>
        <Link href="/"><Wordmark /></Link>
        <Link href="/dashboard" style={{ fontFamily: 'DM Sans, sans-serif', fontSize: '14px', color: '#111010' }}>Dashboard →</Link>
      </nav>

      <main className="max-w-2xl mx-auto px-6 py-12">
        <p className="label mb-2">Legal</p>
        <h1 className="text-5xl mb-2" style={{ fontFamily: 'Fraunces, serif', letterSpacing: '-0.03em' }}>Terms of Service</h1>
        <p className="label mb-8" style={{ color: '#8A8786' }}>Last updated June 2, 2026 · Cole Ventures Group LLC</p>

        <Section title="Agreement to Terms">
          <p>By accessing or using Zovo at getzovo.app, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform. Zovo is operated by Cole Ventures Group LLC, a California LLC (EIN 42-2880704), doing business as Zovo.</p>
        </Section>

        <Section title="What Zovo Is">
          <p>Zovo is a music career platform for independent artists. It provides dashboard analytics (via Spotify), AI-powered playlist curator pitch generation, and music distribution tools. Zovo is a software platform, not a talent agency or label.</p>
        </Section>

        <Section title="Eligibility">
          <p>You must be at least 13 years old to use Zovo. By creating an account, you represent that you meet this requirement and that the information you provide is accurate.</p>
        </Section>

        <Section title="Your Account">
          <p>You are responsible for maintaining the confidentiality of your account credentials. Notify us immediately at support@getzovo.app if you suspect unauthorized access. You are responsible for all activity under your account.</p>
        </Section>

        <Section title="Subscriptions and Billing">
          <ul className="space-y-2 mb-3">
            <li><span style={{ color: '#E8440A' }}>—</span> <strong>Free:</strong> $0/month. 3 curator pitches per month.</li>
            <li><span style={{ color: '#E8440A' }}>—</span> <strong>Artist:</strong> $29/month or $278/year. Unlimited pitches and AI generation.</li>
            <li><span style={{ color: '#E8440A' }}>—</span> <strong>Pro:</strong> $149/month or $1,430/year. Includes music distribution and advanced tools.</li>
          </ul>
          <p className="mb-2">Subscriptions auto-renew unless canceled. You may cancel anytime from Settings. Cancellations take effect at the end of your billing period — no partial refunds. Payments processed by Stripe. We may adjust pricing with 30 days notice.</p>
        </Section>

        <Section title="Spotify Integration">
          <p>Zovo connects to Spotify via OAuth with your explicit permission. We access only the scopes you authorize. You may revoke access at any time via Spotify&apos;s account settings. We comply with Spotify&apos;s Developer Policy and do not use your Spotify data for advertising or AI training.</p>
        </Section>

        <Section title="AI-Generated Content">
          <p>Pitch emails generated by Zovo&apos;s AI (powered by Anthropic Claude) are suggestions only. You are responsible for reviewing, editing, and approving any content before sending. We do not guarantee that AI-generated pitches will be successful or accepted by curators.</p>
        </Section>

        <Section title="Acceptable Use">
          <p>You may not use Zovo to send spam, impersonate others, transmit malware, or violate any applicable law. We reserve the right to suspend accounts that abuse the platform.</p>
        </Section>

        <Section title="Intellectual Property">
          <p>Zovo and its content are owned by Cole Ventures Group LLC. You retain all rights to your music and creative content. By using Zovo, you grant us a limited license to display your content within the platform solely to provide the service.</p>
        </Section>

        <Section title="Music Distribution">
          <p>Distribution features are provided on a best-effort basis. We do not guarantee placement on any platform. You represent that you own or have licensed all rights to music you submit for distribution.</p>
        </Section>

        <Section title="Disclaimers">
          <p>Zovo is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. We do not guarantee uninterrupted service, curator responses, or specific results from using the platform.</p>
        </Section>

        <Section title="Limitation of Liability">
          <p>To the fullest extent permitted by law, Cole Ventures Group LLC shall not be liable for indirect, incidental, or consequential damages. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.</p>
        </Section>

        <Section title="Indemnification">
          <p>You agree to indemnify and hold harmless Cole Ventures Group LLC from claims arising from your use of Zovo, your content, or your violation of these terms.</p>
        </Section>

        <Section title="Termination">
          <p>We may suspend or terminate your account for violations of these terms. You may delete your account at any time from Settings. Upon termination, your access ends and your data is deleted per our Privacy Policy.</p>
        </Section>

        <Section title="Governing Law">
          <p>These terms are governed by the laws of the State of California, without regard to conflict of law principles. Disputes shall be resolved in the courts of California.</p>
        </Section>

        <Section title="Changes to Terms">
          <p>We may update these terms at any time. Continued use of Zovo after changes constitutes acceptance. We will notify you of material changes via email.</p>
        </Section>

        <Section title="Contact">
          <p>Questions? Contact us at <a href="mailto:support@getzovo.app" style={{ color: '#E8440A' }}>support@getzovo.app</a>. Cole Ventures Group LLC, California.</p>
        </Section>
      </main>

      <footer className="px-8 py-6 flex items-center justify-between" style={{ borderTop: '1px solid #E2DED8' }}>
        <Wordmark size="sm" />
        <div className="flex items-center gap-4 text-sm" style={{ color: '#8A8786' }}>
          <Link href="/privacy" style={{ color: '#8A8786' }}>Privacy</Link>
          <a href="mailto:support@getzovo.app" style={{ color: '#8A8786' }}>support@getzovo.app</a>
        </div>
      </footer>
    </div>
  )
}
